version: '3.9'

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
  # local network:
  intnet:
    external: false
    name: ${INT_NETWORK}
  # for elastic
  nginxnet:
    external: true
    name: "nginx.local"

services:
  webwp:
    # Alpine
    # image: lhsradek/lhsdock:v3
    image: nginx:alpine
    container_name: "${APP_ID}-webwp"
    hostname: "webwp.${INT_NETWORK}"
    restart: ${DOCKER_RESTART_POLICY}
    # ports:
    #  - 80:80
    #  - 4443:443
    networks:
      # for traefik:
      - default
      # local network:
      - intnet
    volumes:
      # The first mount add bash and ping to nginx:alpine - lhsradek/lhsdock this dont'n need, see:
      # https://github.com/lhsradek/platypus-lhsdock/blob/main/context/Dockerfile of lhsradek/lhsdock:v3
      - ./extras/nginx/add.sh:/docker-entrypoint.d/05-add-packages.sh
      - ./logs/wordpress-nginx:/var/log/nginx:rw
      - ./extras/nginx/default-https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/ca.crt:/etc/ssl/private/ca.pem:ro
      - ./certs/${CERTNAME}.crt:/etc/ssl/private/cacert.pem:ro
      - ./certs/${CERTNAME}.key:/etc/ssl/private/cacert-key.pem:ro
      - wordpress:/var/www/html/wp:rw
      - phpmyadmin:/var/www/html/pma:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.webwp-${NUM}-public.rule=Host(`${APP_HOST}`, `${WP_PHP_MY_ADMIN_HOST}`)"
      - "traefik.http.routers.webwp-${NUM}-public.entrypoints=https"
      - "traefik.http.routers.webwp-${NUM}-public.tls=true"
      - "traefik.http.services.weblhs-platypus-${APP_ID}.loadbalancer.server.port=443"
      - "traefik.http.services.weblhs-platypus-${APP_ID}.loadbalancer.server.scheme=https"
      # fi
    healthcheck:
      test: "curl -s -I http://localhost/nginx_status | grep -q 'HTTP/1.1 200 OK'"
      interval: 10s
      timeout: 20s
      retries: 50

  webwp-php:
    # Alpine WORDPRESS-php for install or update
    # image: wordpress:fpm-alpine
    # with elastic-apm-php agent https://www.elastic.co/guide/en/apm/agent/php/current/intro.html
    # https://github.com/lhsradek/platypus-lhsfpm/blob/main/context/Dockerfile
    # for https://github.com/lhsradek/platypus-lhsdock
    image: lhsradek/fpm:v1
    container_name: "${APP_ID}-webwp-php"
    # hostname: "webwp-php"
    hostname: "webwp-php.${INT_NETWORK}"
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      # local network:
      - intnet
      # for elastic apm
      - nginxnet
    environment:
      - ELASTIC_APM_ENVIRONMENT=${STAGE}
      - ELASTIC_APM_HOSTNAME=webwp-php.${INT_NETWORK}
      - ELASTIC_APM_LOG_LEVEL_STDERR=info
      - ELASTIC_APM_SECRET_TOKEN=${ELASTIC_APM_SECRET_TOKEN}
      - ELASTIC_APM_SERVER_URL=http://apm.nginx.local:8200
      - ELASTIC_APM_SERVICE_NAME=${APP_NICK}-${APP_ID}
      - ELASTIC_APM_SERVICE_NODE_NAME=wp.${APP_HOST}
      - WORDPRESS_DB_HOST=db.${APP_HOST}
      - WORDPRESS_DB_NAME=${APP_ID}
      - WORDPRESS_DB_USER=${APP_ID}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
      - |
        WORDPRESS_CONFIG_EXTRA=
        define( 'MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL ); 
        define( 'WP_HOME', "${WP_HOME}" );
        define( 'WP_SITEURL', "${WP_HOME}" );
        define( 'WP_ENVIRONMENT_TYPE', "${ENVIRONMENT_TYPE}" );
        define( 'WP_REDIS_HOST', "redis" );
    volumes:
      - ./certs/ca.crt:/var/www/html/wp-includes/certificates/rootCA.crt:ro
      # - ./certs/${CERTNAME}.crt:/var/www/html/wp-includes/certificates/${APP_HOST}.crt:ro
      # - ./certs/${CERTNAME}.key:/var/www/html/wp-includes/certificates/${APP_HOST}.key:ro
      - wordpress:/var/www/html:rw

  webpma-php:
    # Alpine phpMyAdmin
    image: phpmyadmin:fpm-alpine
    container_name: "${APP_ID}-webpma-php"
    hostname: "pma.${APP_HOST}"
    restart: ${DOCKER_RESTART_POLICY}
    environment:
      - PMA_HOST=db.${APP_HOST}
      - PMA_ARBITRARY=0
      - UPLOAD_LIMIT=1280M
    networks:
      # local network:
      - intnet
    volumes:
      - ./extras/pma/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
      - ./certs/ca.crt:/etc/phpmyadmin/cacert.pem:ro
      - ./certs/${PMA_CERTNAME}.crt:/etc/phpmyadmin/cert.pem:ro
      - ./certs/${PMA_CERTNAME}.key:/etc/phpmyadmin/cert-key.pem:ro
      - phpmyadmin:/var/www/html:rw

  db:
    # Ubuntu - db 
    image: mariadb
    container_name: "${APP_ID}-db"
    hostname: "db.${APP_HOST}"
    restart: ${DOCKER_RESTART_POLICY}
    ports:
      - 3306:3306
    networks:
      # local network:
      - intnet
      # for elastic beats
      - nginxnet
    environment:
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_ID}
      MYSQL_USER: ${APP_ID}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: "true"
    volumes:
      - ./logs/wordpress-mysql:/var/log/mysql:rw
      - ./extras/etc/mysql/mariadb.conf.d/50-server-ssl.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
      - ./certs/ca.crt:/etc/mysql/cacert.pem:ro
      - ./certs/${DB_CERTNAME}.crt:/etc/mysql/server-cert.pem:ro
      - ./certs/${DB_CERTNAME}.key:/etc/mysql/server-key.pem:ro
      - mysql:/var/lib/mysql:rw

  redis:
    # Alpine Linux
    image: redis:7-alpine
    container_name: "${APP_ID}-redis"
    # hostname: "redis.${INT_NETWORK}"
    hostname: "redis"
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      # local network:
      - intnet
      # for elastic beats
      - nginxnet
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    # ports:
    # - 6379:6379
    volumes:
      # - ./extras/etc/sysctl.conf:/etc/sysctl.conf:ro
      # - ./extras/redis/redis.conf:/usr/local/etc/redis/redis.conf
      # - ./extras/var/lib/sysctl.d/00-alpine.conf:/var/lib/sysctl.d/00-alpine.conf:rw
      # - ./certs/ca.crt:/etc/ssl/private/ca.crt:ro
      # - ./certs/${REDIS_CERTNAME}.crt:/etc/ssl/private/cacert.crt:ro
      # - ./certs/${REDIS_CERTNAME}.key:/etc/ssl/private/cacert.key:ro
      - redis:/data:rw

#       
#   Redis Commander - Web Console for Redis
#        
#   webwp-rc:
#     image: rediscommander/redis-commander:latest
#     container_name: "${APP_ID}-webrc"
#     hostname: "rc.${APP_HOST}"
#     # build: .
#     restart: ${DOCKER_RESTART_POLICY}
#     networks:
#       # for traefik:
#       - default
#       # local network:
#       - intnet
#     environment:
#       - REDIS_HOSTS=redis
#     #ports:
#     # - "8081:8081"
#     labels:
#       - "traefik.enable=true"
#       - "traefik.docker.network=${DOCKER_NETWORK}"
#       - "traefik.http.routers.webwp-rc-${NUM}-public.rule=Host(`rc.${APP_HOST}`)"
#       - "traefik.http.routers.webwp-rc-${NUM}-public.entrypoints=https"
#       - "traefik.http.routers.webwp-rc-${NUM}-public.tls=true"
#       - "traefik.http.services.webwp-rc-platypus-${APP_ID}.loadbalancer.server.port=8081"
#       - "traefik.http.services.webwp-rc-platypus-${APP_ID}.loadbalancer.server.scheme=http"
   
volumes:
  wordpress:
    external: true
    name: "${NAME}-wp-${NUM}"
  phpmyadmin:
    external: true
    name: "${NAME}-pma-${NUM}"
  mysql:
    external: true
    name: "${NAME}-db-${NUM}"
  redis:
    external: true
    name: "${NAME}-redis-${NUM}"
