version: '3.1'

volumes:
  mysql:
    external: false
    name: "mysql-${NAME}"
  wordpress:
    external: false
    name: "${APP_ID}"

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

services:
  db:
    # Ubuntu
    image: mariadb
    container_name: "${APP_ID}-db"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${APP_ID}"
      MYSQL_USER: "${APP_ID}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - 3306:3306
    volumes:
      - /root/bin/ubuntu:/root/bin/ubuntu:ro
      - ./context/root/bin:/root/bin:rw
      - mysql:/var/lib/mysql

  nginx:
    # Alpine
    image: nginx:alpine
    container_name: "${APP_ID}-webserver"
    restart: "no"
    environment:
      - NGINX_HOST=$APP_HOST
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - wordpress:/var/www/html:rw
      - type: bind
        source: ./extras/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-public.tls=true"
    links:
      - wordpress

  wordpress:
    # Alpine Linux
    image: wordpress:fpm-alpine
    container_name: "${APP_ID}-php"
    restart: "no"
    environment:
      WORDPRESS_DB_HOST: "${APP_HOST}"
      WORDPRESS_DB_USER: "${APP_ID}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${APP_ID}"
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - wordpress:/var/www/html:rw
      - type: bind
        source: ./application/html/wordpress/wp-config.php
        target: /var/www/html/wp-config.php
        read_only: true
