version: '3.1'

volumes:
  mysql:
    external: false
    name: "${NAME}-db-${NUM}"
  wordpress:
    external: false
    name: "${APP_ID}"
  phpmyadmin:
    external: true
    name: "${NAME}-pma-${NUM}"

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}

services:
  nginx:
    # Alpine
    image: nginx:alpine
    container_name: "${APP_ID}-webserver"
    hostname: ${APP_HOST}
    restart: "no"
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - wordpress:/var/www/html:rw
      - type: bind
        source: ./extras/nginx/conf.d/wordpress/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-public.tls=true"
    links:
      - wordpress

  nginx-webpma:
    # Alpine
    image: nginx:alpine
    container_name: "${APP_ID}-webpma"
    hostname: ${APP_PMA}
    restart: "no"
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - phpmyadmin:/var/www/html:rw
      - type: bind
        source: ./extras/nginx/conf.d/pma/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./application/html/pma/config.inc.php
        target: /var/www/html/config.inc.php
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-webpma-public.rule=Host(`${APP_PMA}`)"
      - "traefik.http.routers.${APP_ID}-webpma-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-webpma-public.tls=true"
    links:
      - phpmyadmin

  phpmyadmin:
    # Alpine
    image: phpmyadmin:fpm-alpine
    container_name: "${APP_ID}-pma"
    hostname: ${APP_PMA}
    restart: "no"
    # restart: always
    # ports:
    #  - 9000:9000
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_ARBITRARY=0
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - phpmyadmin:/var/www/html:rw
      - type: bind
        source: ./application/html/pma/config.inc.php
        target: /var/www/html/config.inc.php
        read_only: true

  wordpress:
    # Alpine Linux
    image: wordpress:fpm-alpine
    container_name: "${APP_ID}-php"
    hostname: ${APP_HOST}
    restart: "no"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${APP_ID}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${APP_ID}
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - wordpress:/var/www/html:rw
      - type: bind
        source: ./application/html/wordpress/wp-config.php
        target: /var/www/html/wp-config.php
        read_only: true

  db:
    # Ubuntu
    image: mariadb
    container_name: "${APP_ID}-db"
    hostname: ${DB_HOST}
    restart: "no"
    # ports:
    #  - 3306:3306
    environment:
      # MYSQL_ROOT_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_ID}
      MYSQL_USER: ${APP_ID}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /root/bin/ubuntu:/root/bin/ubuntu:ro
      - ./context/root/bin:/root/bin:rw
      - mysql:/var/lib/mysql
