version: '3.9'

volumes:
  mysql:
    external: true
    name: "${NAME}-db-${NUM}"
  wordpress:
    external: true
    name: "${APP_ID}"
  phpmyadmin:
    external: true
    name: "${NAME}-pma-${NUM}"

networks:
  default:
    external: true
    name: ${DOCKER_NETWORK}
  # common intranet network:
  intnet:
    external: false
    name: ${INT_NETWORK}

services:
  nginx-webwp:
    # Alpine WORDPRESS
    image: nginx:alpine
    # image: lhsradek/lhsdock:v3
    container_name: "${APP_ID}-webwp"
    hostname: "${APP_HOST}-webwp"
    # restart: "no"
    restart: always
    # ports:
    #  - 4443:443
    networks:
      - intnet
      # for traefik:
      - default
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - wordpress:/var/www/html:rw
      - type: bind
        source: ./extras/nginx/wordpress/default-https.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./extras/nginx/pki/${CERTNAME}.pem
        target: /etc/ssl/private/cacert.pem
        read_only: true
      - type: bind
        source: ./extras/nginx/pki/${CERTNAME}-key.pem
        target: /etc/ssl/private/cacert-key.pem
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-webwp-public.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-webwp-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-webwp-public.tls=true"
      - "traefik.http.services.nginx-webwp-platypus-${NAME}-mysql.loadbalancer.server.scheme=https"
      - "traefik.http.services.nginx-webwp-platypus-${NAME}-mysql.loadbalancer.server.port=443"
    links:
      - nginx-pwp

  nginx-webpma:
    # Alpine phpMyAdmin
    image: nginx:alpine
    # image: lhsradek/lhsdock:v3
    container_name: "${APP_ID}-webpma"
    hostname: "pma.${APP_HOST}"
    # restart: "no"
    restart: always
    networks:
      - intnet
      # for traefik:
      - default
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - phpmyadmin:/var/www/html:rw
      - type: bind
        source: ./extras/nginx/pma/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./application/html/pma/config.inc.php
        target: /var/www/html/config.inc.php
        read_only: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKER_NETWORK}"
      - "traefik.http.routers.${APP_ID}-webpma-public.rule=Host(`pma.${APP_HOST}`)"
      - "traefik.http.routers.${APP_ID}-webpma-public.entrypoints=https"
      - "traefik.http.routers.${APP_ID}-webpma-public.tls=true"
    links:
      - nginx-pma

  nginx-pwp:
    # Alpine WORDPRESS
    image: wordpress:fpm-alpine
    container_name: "${APP_ID}-pwp"
    hostname: "${APP_ID}-pwp.${INT_NETWORK}"
    # restart: "no"
    restart: always
    environment:
      # - WORDPRESS_DB_HOST=${APP_ID}-db.${INT_NETWORK}
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${APP_ID}
      - WORDPRESS_DB_USER=${APP_ID}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
      - HEADLESS_FRONTEND_URL=${HEADLESS_FRONTEND_URL}
      - WP_HOME=https://${APP_HOST}
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - wordpress:/var/www/html:rw
        # - ./application/html/wordpress/wp-config.php:/var/www/html/wp-config.php:rw
        # - ./application/html/wordpress/wp-includes/class-wp-http.php:/var/www/html/wp-includes/class-wp-http.php:rw
        # - ./application/html/wordpress/wp-includes/update.php:/var/www/html/wp-includes/update.php:rw
    networks:
      - intnet

  nginx-pma:
    # Alpine phpMyAdmin php
    image: phpmyadmin:fpm-alpine
    container_name: "${APP_ID}-pma"
    hostname: "${APP_ID}-pma.${INT_NETWORK}"
    # restart: "no"
    restart: always
    # restart: always
    environment:
      # - PMA_HOST=${APP_ID}-db.${INT_NETWORK}
      - PMA_HOST=db
      - PMA_ARBITRARY=0
    networks:
      - intnet
    volumes:
      - /root/bin/alpine:/root/bin/alpine:ro
      - ./context/root/bin:/root/bin:rw
      - phpmyadmin:/var/www/html:rw
      - type: bind
        source: ./application/html/pma/config.inc.php
        target: /var/www/html/config.inc.php
        read_only: true

  db:
    # Ubuntu - db 
    image: mariadb
    container_name: "${APP_ID}-db"
    hostname: "${APP_ID}-db.${INT_NETWORK}"
    # restart: "no"
    restart: always
    # ports:
    #  - 3306:3306
    networks:
      - intnet
    environment:
      MYSQL_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${APP_ID}
      MYSQL_USER: ${APP_ID}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
    volumes:
      - /root/bin/ubuntu:/root/bin/ubuntu:ro
      - ./context/root/bin:/root/bin:rw
      - mysql:/var/lib/mysql
